-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "mellifluous"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#cbaa88" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@constant.builtin", { link = "Constant" })
hi(0, "@constant.macro", { link = "Constant" })
hi(0, "@constructor", { link = "Function" })
hi(0, "@danger", { fg = "#d59192" })
hi(0, "@debug", { fg = "#cbaa88" })
hi(0, "@define", { link = "PreProc" })
hi(0, "@environment", { fg = "#cbaa88" })
hi(0, "@environment.name", { link = "@environment" })
hi(0, "@error", { link = "Error" })
hi(0, "@field", { fg = "#dadada" })
hi(0, "@function.builtin", { link = "Function" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@include", { link = "Function" })
hi(0, "@keyword.function", { fg = "#d59192" })
hi(0, "@keyword.operator", { fg = "#cbaa88" })
hi(0, "@keyword.return", { fg = "#d59192" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.enum", { link = "Type" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.escapeSequence", { fg = "#848484" })
hi(0, "@lsp.type.formatSpecifier", { link = "Operator" })
hi(0, "@lsp.type.namespace", { link = "Type" })
hi(0, "@lsp.type.operator", { link = "Operator" })
hi(0, "@lsp.type.parameter", {})
hi(0, "@lsp.type.property", { fg = "#dadada" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.keyword.controlFlow", { fg = "#d59192" })
hi(0, "@lsp.typemod.variable.constant", { link = "Constant" })
hi(0, "@math", { fg = "#cbaa88" })
hi(0, "@namespace", { link = "Type" })
hi(0, "@neorg.anchors.declaration", { link = "@text.reference" })
hi(0, "@neorg.anchors.declaration.delimiter", { link = "NonText" })
hi(0, "@neorg.anchors.definition.delimiter", { link = "NonText" })
hi(0, "@neorg.definitions.content", { link = "@text.emphasis" })
hi(0, "@neorg.definitions.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.definitions.suffix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.definitions.title", { link = "@text.strong" })
hi(0, "@neorg.delimiters.horizontal_line", { link = "@punctuation.delimiter" })
hi(0, "@neorg.delimiters.strong", { link = "@punctuation.delimiter" })
hi(0, "@neorg.delimiters.weak", { link = "@punctuation.delimiter" })
hi(0, "@neorg.error", { link = "@error" })
hi(0, "@neorg.footnotes.content", { link = "@text.emphasis" })
hi(0, "@neorg.footnotes.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.footnotes.suffix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.footnotes.title", { link = "@text.strong" })
hi(0, "@neorg.headings.1.prefix", { link = "@attribute" })
hi(0, "@neorg.headings.1.title", { link = "@attribute" })
hi(0, "@neorg.headings.2.prefix", { link = "@label" })
hi(0, "@neorg.headings.2.title", { link = "@label" })
hi(0, "@neorg.headings.3.prefix", { link = "@constant" })
hi(0, "@neorg.headings.3.title", { link = "@constant" })
hi(0, "@neorg.headings.4.prefix", { link = "@string" })
hi(0, "@neorg.headings.4.title", { link = "@string" })
hi(0, "@neorg.headings.5.prefix", { link = "@label" })
hi(0, "@neorg.headings.5.title", { link = "@label" })
hi(0, "@neorg.headings.6.prefix", { link = "@constructor" })
hi(0, "@neorg.headings.6.title", { link = "@constructor" })
hi(0, "@neorg.links.description", { link = "@text.uri" })
hi(0, "@neorg.links.description.delimiter", { link = "NonText" })
hi(0, "@neorg.links.file", { link = "@comment" })
hi(0, "@neorg.links.file.delimiter", { link = "NonText" })
hi(0, "@neorg.links.location.definition", { link = "@neorg.definitions.title" })
hi(0, "@neorg.links.location.definition.prefix", { link = "@neorg.definitions.prefix" })
hi(0, "@neorg.links.location.delimiter", { link = "NonText" })
hi(0, "@neorg.links.location.external_file", { link = "@label" })
hi(0, "@neorg.links.location.external_file.prefix", { link = "@label" })
hi(0, "@neorg.links.location.footnote", { link = "@neorg.footnotes.title" })
hi(0, "@neorg.links.location.footnote.prefix", { link = "@neorg.footnotes.prefix" })
hi(0, "@neorg.links.location.generic", { link = "@type" })
hi(0, "@neorg.links.location.generic.prefix", { link = "@type" })
hi(0, "@neorg.links.location.heading.1", { link = "@neorg.headings.1.title" })
hi(0, "@neorg.links.location.heading.1.prefix", { link = "@neorg.headings.1.prefix" })
hi(0, "@neorg.links.location.heading.2", { link = "@neorg.headings.2.title" })
hi(0, "@neorg.links.location.heading.2.prefix", { link = "@neorg.headings.2.prefix" })
hi(0, "@neorg.links.location.heading.3", { link = "@neorg.headings.3.title" })
hi(0, "@neorg.links.location.heading.3.prefix", { link = "@neorg.headings.3.prefix" })
hi(0, "@neorg.links.location.heading.4", { link = "@neorg.headings.4.title" })
hi(0, "@neorg.links.location.heading.4.prefix", { link = "@neorg.headings.4.prefix" })
hi(0, "@neorg.links.location.heading.5", { link = "@neorg.headings.5.title" })
hi(0, "@neorg.links.location.heading.5.prefix", { link = "@neorg.headings.5.prefix" })
hi(0, "@neorg.links.location.heading.6", { link = "@neorg.headings.6.title" })
hi(0, "@neorg.links.location.heading.6.prefix", { link = "@neorg.headings.6.prefix" })
hi(0, "@neorg.links.location.marker", { link = "@neorg.markers.title" })
hi(0, "@neorg.links.location.marker.prefix", { link = "@neorg.markers.prefix" })
hi(0, "@neorg.links.location.url", { link = "@text.uri" })
hi(0, "@neorg.lists.ordered.prefix", { link = "@repeat" })
hi(0, "@neorg.lists.unordered.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.markup.bold", { link = "@text.strong" })
hi(0, "@neorg.markup.bold.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.free_form_delimiter", { link = "NonText" })
hi(0, "@neorg.markup.inline_comment", { fg = "#828282" })
hi(0, "@neorg.markup.inline_comment.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.inline_math", { link = "@text.math" })
hi(0, "@neorg.markup.inline_math.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.italic", { link = "@text.emphasis" })
hi(0, "@neorg.markup.italic.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.spoiler", { link = "@text.danger" })
hi(0, "@neorg.markup.spoiler.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.strikethrough", { strikethrough = true })
hi(0, "@neorg.markup.strikethrough.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.subscript", { link = "@label" })
hi(0, "@neorg.markup.subscript.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.superscript", { link = "@number" })
hi(0, "@neorg.markup.superscript.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.underline", { underline = true })
hi(0, "@neorg.markup.underline.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.variable", { link = "@function.macro" })
hi(0, "@neorg.markup.variable.delimiter", { link = "NonText" })
hi(0, "@neorg.markup.verbatim", { fg = "#aeaeae" })
hi(0, "@neorg.markup.verbatim.delimiter", { link = "NonText" })
hi(0, "@neorg.modifiers.escape", { link = "@type" })
hi(0, "@neorg.modifiers.link", { link = "NonText" })
hi(0, "@neorg.quotes.1.content", { link = "@punctuation.delimiter" })
hi(0, "@neorg.quotes.1.prefix", { link = "@punctuation.delimiter" })
hi(0, "@neorg.quotes.2.content", { link = "Blue" })
hi(0, "@neorg.quotes.2.prefix", { link = "Blue" })
hi(0, "@neorg.quotes.3.content", { link = "Yellow" })
hi(0, "@neorg.quotes.3.prefix", { link = "Yellow" })
hi(0, "@neorg.quotes.4.content", { link = "Red" })
hi(0, "@neorg.quotes.4.prefix", { link = "Red" })
hi(0, "@neorg.quotes.5.content", { link = "Green" })
hi(0, "@neorg.quotes.5.prefix", { link = "Green" })
hi(0, "@neorg.quotes.6.content", { link = "Brown" })
hi(0, "@neorg.quotes.6.prefix", { link = "Brown" })
hi(0, "@neorg.selection_window.arrow", { link = "@none" })
hi(0, "@neorg.selection_window.heading", { link = "@annotation" })
hi(0, "@neorg.selection_window.key", { link = "@namespace" })
hi(0, "@neorg.selection_window.keyname", { link = "@constant" })
hi(0, "@neorg.selection_window.nestedkeyname", { link = "@string" })
hi(0, "@neorg.tags.carryover.begin", { link = "@label" })
hi(0, "@neorg.tags.carryover.name", { link = "@none" })
hi(0, "@neorg.tags.carryover.name.delimiter", { link = "@none" })
hi(0, "@neorg.tags.carryover.name.word", { link = "@label" })
hi(0, "@neorg.tags.carryover.parameters", { link = "@string" })
hi(0, "@neorg.tags.comment.content", { link = "@comment" })
hi(0, "@neorg.tags.ranged_verbatim.begin", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.code_block", { bg = "#161616" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.bracket", { link = "@punctuation.bracket" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.value", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.authors", { link = "@annotation" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.categories", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.created", { link = "@float" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.description", { link = "@label" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.key", { link = "@field" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.number", { link = "@number" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.object.bracket", { link = "@punctuation.bracket" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.title", { link = "@text.title" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.trailing", { link = "@repeat" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.updated", { link = "@float" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.value", { link = "@string" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.version", { link = "@float" })
hi(0, "@neorg.tags.ranged_verbatim.end", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.name", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.name.delimiter", { link = "@none" })
hi(0, "@neorg.tags.ranged_verbatim.name.word", { link = "@keyword" })
hi(0, "@neorg.tags.ranged_verbatim.parameters", { link = "@type" })
hi(0, "@neorg.todo_items.cancelled", { link = "NonText" })
hi(0, "@neorg.todo_items.done", { link = "@string" })
hi(0, "@neorg.todo_items.on_hold", { link = "@text.note" })
hi(0, "@neorg.todo_items.pending", { link = "@namespace" })
hi(0, "@neorg.todo_items.recurring", { link = "@repeat" })
hi(0, "@neorg.todo_items.uncertain", { link = "@boolean" })
hi(0, "@neorg.todo_items.undone", { link = "@punctuation.delimiter" })
hi(0, "@neorg.todo_items.urgent", { link = "@text.danger" })
hi(0, "@parameter", { fg = "#dadada" })
hi(0, "@parameter.reference", { link = "@parameter" })
hi(0, "@property", { link = "@field" })
hi(0, "@punctuation.bracket", { link = "Operator" })
hi(0, "@punctuation.delimiter", { link = "Operator" })
hi(0, "@punctuation.special", { link = "Operator" })
hi(0, "@storage.class", { link = "StorageClass" })
hi(0, "@string.escape", { link = "Character" })
hi(0, "@string.regex", { link = "Character" })
hi(0, "@string.special", { link = "Character" })
hi(0, "@symbol", { link = "Character" })
hi(0, "@tag", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "Function" })
hi(0, "@tag.delimiter", { link = "Operator" })
hi(0, "@text.danger", { bg = "#37302a", fg = "#aa8a69" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Character" })
hi(0, "@text.reference", { fg = "#b99bb5" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { fg = "#cbaa88" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#817a95" })
hi(0, "@text.warning", { bg = "#3b2e2e", fg = "#be7c7d" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@variable.builtin", { fg = "#cbaa88" })
hi(0, "@warning", { fg = "#cbaa88" })
hi(0, "Character", { fg = "#bfaf8e" })
hi(0, "CmpDocumentationBorder", { bg = "#2d2d2d" })
hi(0, "CmpItemAbbr", { fg = "#848484" })
hi(0, "CmpItemAbbrDefault", { fg = "#848484" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#737246" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#737246" })
hi(0, "CmpItemAbbrMatch", { fg = "#dadada" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#848484" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#dadada" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#848484" })
hi(0, "CmpItemKind", { fg = "#bfad9d" })
hi(0, "CmpItemKindClass", { fg = "#bfad9d" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { fg = "#d59192" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = "#b99bb5" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = "#a8a1be" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#cbaa88" })
hi(0, "CmpItemKindEnum", { fg = "#b99bb5" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = "#b99bb5" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = "#d59192" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = "#dadada" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { fg = "#a8a1be" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { fg = "#a8a1be" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = "#a8a1be" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = "#bfad9d" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = "#cbaa88" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = "#a8a1be" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = "#a8a1be" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = "#bfad9d" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = "#dadada" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = "#bfad9d" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = "#cbaa88" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = "#bfad9d" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#bfaf8e" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = "#bfad9d" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = "#bfad9d" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = "#b99bb5" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#dadada" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#848484" })
hi(0, "CmpItemMenuDefault", { fg = "#848484" })
hi(0, "ColorColumn", { bg = "#141414" })
hi(0, "Comment", { fg = "#737246", italic = true })
hi(0, "Conceal", { fg = "#4d4d4d" })
hi(0, "Conditional", { fg = "#d59192" })
hi(0, "Constant", { fg = "#b99bb5" })
hi(0, "Cursor", { bg = "#cbaa88", fg = "#1a1a1a" })
hi(0, "CursorColumn", { bg = "#242424" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#242424" })
hi(0, "CursorLineNr", { bg = "#1e1e1e", fg = "#5b5b5b" })
hi(0, "Delimiter", { link = "Operator" })
hi(0, "DiagnosticError", { fg = "#be7c7d" })
hi(0, "DiagnosticHint", { fg = "#a3869f" })
hi(0, "DiagnosticInfo", { fg = "#938ca8" })
hi(0, "DiagnosticSignError", { bg = "#141414", fg = "#be7c7d" })
hi(0, "DiagnosticSignHint", { bg = "#141414", fg = "#a3869f" })
hi(0, "DiagnosticSignInfo", { bg = "#141414", fg = "#938ca8" })
hi(0, "DiagnosticSignWarn", { bg = "#141414", fg = "#aa8a69" })
hi(0, "DiagnosticUnderlineError", { underline = true })
hi(0, "DiagnosticUnderlineHint", { underline = true })
hi(0, "DiagnosticUnderlineInfo", { underline = true })
hi(0, "DiagnosticUnderlineWarn", { underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#2e2626", fg = "#be7c7d" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2a272a", fg = "#a3869f" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#29282b", fg = "#938ca8" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2b2723", fg = "#aa8a69" })
hi(0, "DiagnosticWarn", { fg = "#aa8a69" })
hi(0, "DiffAdd", { bg = "#2d2d21" })
hi(0, "DiffChange", { bg = "#342a1f" })
hi(0, "DiffDelete", { bg = "#3d2425" })
hi(0, "DiffText", { bg = "#4a3a28" })
hi(0, "Directory", { fg = "#a8a1be" })
hi(0, "EndOfBuffer", { fg = "#1a1a1a" })
hi(0, "Error", { fg = "#d59192" })
hi(0, "ErrorMsg", { fg = "#d59192" })
hi(0, "Exception", { fg = "#cbaa88" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#282828", fg = "#282828" })
hi(0, "FloatShadow", { bg = "#141414" })
hi(0, "FloatTitle", { bg = "#282828", fg = "#737246" })
hi(0, "FoldColumn", { link = "Normal" })
hi(0, "Folded", { bg = "#282828", fg = "#848484" })
hi(0, "Function", { fg = "#a8a1be" })
hi(0, "GitSignsAdd", { bg = "#141414", fg = "#616136" })
hi(0, "GitSignsChange", { bg = "#141414", fg = "#b07534" })
hi(0, "GitSignsDelete", { bg = "#141414", fg = "#a7474e" })
hi(0, "Identifier", { fg = "#dadada" })
hi(0, "Ignore", { fg = "#4d4d4d" })
hi(0, "IncSearch", { bg = "#cbaa88", fg = "#1a1a1a" })
hi(0, "IndentBlanklineChar", { fg = "#2d2d2d" })
hi(0, "IndentBlanklineContextChar", { fg = "#4d4d4d" })
hi(0, "IndentBlanklineSpaceChar", { link = "Whitespace" })
hi(0, "Keyword", { fg = "#cbaa88" })
hi(0, "Label", { fg = "#d59192" })
hi(0, "LineNr", { bg = "#141414", fg = "#5b5b5b" })
hi(0, "LspCodeLens", { bg = "#242424" })
hi(0, "LspCodeLensSeparator", { fg = "#4d4d4d" })
hi(0, "LspInfoBorder", { fg = "#d59192" })
hi(0, "LspInfoFiletype", { fg = "#bfad9d" })
hi(0, "LspInfoList", { fg = "#a8a1be" })
hi(0, "LspInfoTip", { fg = "#737246", italic = true })
hi(0, "LspInfoTitle", { fg = "#cbaa88" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#282828" })
hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
hi(0, "LspSignatureActiveParameter", { bg = "#2d2d2d" })
hi(0, "MatchParen", { bg = "#2d2d2d", fg = "#d59192" })
hi(0, "ModeMsg", { fg = "#848484" })
hi(0, "MoreMsg", { fg = "#cbaa88" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { link = "VertSplit" })
hi(0, "NonText", { link = "Conceal" })
hi(0, "Normal", { bg = "#1a1a1a", fg = "#dadada" })
hi(0, "NormalFloat", { bg = "#282828" })
hi(0, "NvimTreeBookmark", { fg = "#b3b393" })
hi(0, "NvimTreeEndOfBuffer", { bg = "#141414", fg = "#1a1a1a" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#b3b393" })
hi(0, "NvimTreeFolderIcon", { fg = "#a8a1be" })
hi(0, "NvimTreeGitDeleted", { fg = "#d59192" })
hi(0, "NvimTreeGitDirty", { fg = "#aa8a69" })
hi(0, "NvimTreeGitIgnored", { fg = "#4d4d4d" })
hi(0, "NvimTreeGitMerge", { fg = "#a3869f" })
hi(0, "NvimTreeGitNew", { fg = "#938ca8" })
hi(0, "NvimTreeGitRenamed", { fg = "#aa8a69" })
hi(0, "NvimTreeGitStaged", { fg = "#939374" })
hi(0, "NvimTreeImageFile", { bold = true, fg = "#b99bb5" })
hi(0, "NvimTreeIndentMarker", { fg = "#a8a1be" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#b99bb5" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeModifiedFile", { fg = "#b3b393" })
hi(0, "NvimTreeNormal", { bg = "#141414", fg = "#aeaeae" })
hi(0, "NvimTreeOpenedFile", { bold = true, fg = "#b3b393" })
hi(0, "NvimTreePopup", { link = "NvimTreeNormal" })
hi(0, "NvimTreeRootFolder", { fg = "#141414" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#bfaf8e", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#a8a1be" })
hi(0, "NvimTreeWinSeparator", { bg = "#141414", fg = "#282828" })
hi(0, "NvimTreeWindowPicker", { bg = "#4493c8", bold = true, fg = "#ededed" })
hi(0, "Operator", { fg = "#bfad9d" })
hi(0, "Pmenu", { bg = "#2d2d2d", fg = "#848484" })
hi(0, "PmenuSbar", { bg = "#282828" })
hi(0, "PmenuSel", { bg = "#4d4d4d" })
hi(0, "PmenuThumb", { bg = "#4d4d4d" })
hi(0, "PreProc", { fg = "#a8a1be" })
hi(0, "Question", { fg = "#cbaa88" })
hi(0, "QuickFixLine", { link = "Normal" })
hi(0, "Repeat", { fg = "#d59192" })
hi(0, "Search", { bg = "#2d2d2d", fg = "#dadada" })
hi(0, "SignColumn", { link = "LineNr" })
hi(0, "Special", { fg = "#cbaa88" })
hi(0, "SpecialKey", { fg = "#cbaa88" })
hi(0, "SpellBad", { fg = "#d59192" })
hi(0, "SpellCap", { fg = "#cbaa88" })
hi(0, "SpellLocal", { fg = "#cbaa88" })
hi(0, "SpellRare", { fg = "#cbaa88" })
hi(0, "StartifyBracket", { fg = "#5b5b5b" })
hi(0, "StartifyEndOfBuffer", { fg = "#1a1a1a" })
hi(0, "StartifyNumber", { fg = "#dadada" })
hi(0, "StartifyPath", { fg = "#a8a1be" })
hi(0, "StartifySlash", { link = "StartifyPath" })
hi(0, "Statement", { fg = "#cbaa88" })
hi(0, "StatusLine", { bg = "#2d2d2d", fg = "#aeaeae" })
hi(0, "StatusLineNC", { bg = "#242424", fg = "#5b5b5b" })
hi(0, "Stl5b5b5b_242424__", { bg = "#242424", fg = "#5b5b5b" })
hi(0, "Stl6d8086_242424__", { bg = "#242424", fg = "#6d8086" })
hi(0, "Stl6d8086_2d2d2d__", { bg = "#2d2d2d", fg = "#6d8086" })
hi(0, "Stlaeaeae_242424__", { bg = "#242424", fg = "#aeaeae" })
hi(0, "Stlaeaeae_2d2d2d__", { bg = "#2d2d2d", fg = "#aeaeae" })
hi(0, "String", { fg = "#bfaf8e" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { bg = "#2d2d2d", fg = "#848484" })
hi(0, "TabLineFill", { link = "TabLine" })
hi(0, "TabLineSel", { bg = "#242424", fg = "#aeaeae" })
hi(0, "TelescopeBorder", { fg = "#242424" })
hi(0, "TelescopeMatching", { fg = "#dadada" })
hi(0, "TelescopeMultiIcon", { fg = "#dadada" })
hi(0, "TelescopeMultiSelection", { fg = "#bfad9d" })
hi(0, "TelescopeNormal", { bg = "#242424", fg = "#848484" })
hi(0, "TelescopePreviewBlock", { fg = "#b99bb5" })
hi(0, "TelescopePreviewBorder", { bg = "#242424", fg = "#242424" })
hi(0, "TelescopePreviewCharDev", { fg = "#b99bb5" })
hi(0, "TelescopePreviewDate", { fg = "#a8a1be" })
hi(0, "TelescopePreviewDirectory", { fg = "#a8a1be" })
hi(0, "TelescopePreviewExecute", { fg = "#bfaf8e" })
hi(0, "TelescopePreviewGroup", { fg = "#b99bb5" })
hi(0, "TelescopePreviewHyphen", { fg = "#4d4d4d" })
hi(0, "TelescopePreviewLine", { bg = "#323232" })
hi(0, "TelescopePreviewLink", { fg = "#cbaa88" })
hi(0, "TelescopePreviewMatch", { bg = "#2d2d2d", fg = "#dadada" })
hi(0, "TelescopePreviewMessage", { bg = "#242424" })
hi(0, "TelescopePreviewMessageFillchar", { bg = "#242424" })
hi(0, "TelescopePreviewNormal", { bg = "#242424" })
hi(0, "TelescopePreviewPipe", { fg = "#b99bb5" })
hi(0, "TelescopePreviewRead", { fg = "#b99bb5" })
hi(0, "TelescopePreviewSize", { fg = "#bfaf8e" })
hi(0, "TelescopePreviewSocket", { fg = "#cbaa88" })
hi(0, "TelescopePreviewSticky", { fg = "#cbaa88" })
hi(0, "TelescopePreviewTitle", { fg = "#848484" })
hi(0, "TelescopePreviewUser", { fg = "#b99bb5" })
hi(0, "TelescopePreviewWrite", { fg = "#cbaa88" })
hi(0, "TelescopePromptBorder", { bg = "#242424", fg = "#242424" })
hi(0, "TelescopePromptCounter", { fg = "#5b5b5b" })
hi(0, "TelescopePromptNormal", { bg = "#242424" })
hi(0, "TelescopePromptPrefix", { fg = "#dadada" })
hi(0, "TelescopePromptTitle", { bg = "#aeaeae", fg = "#1a1a1a" })
hi(0, "TelescopeResultsBorder", { bg = "#242424", fg = "#242424" })
hi(0, "TelescopeResultsClass", { fg = "#a8a1be" })
hi(0, "TelescopeResultsComment", { fg = "#737246", italic = true })
hi(0, "TelescopeResultsConstant", { fg = "#b99bb5" })
hi(0, "TelescopeResultsDiffAdd", { bg = "#2d2d21" })
hi(0, "TelescopeResultsDiffChange", { bg = "#342a1f" })
hi(0, "TelescopeResultsDiffDelete", { bg = "#3d2425" })
hi(0, "TelescopeResultsDiffUntracked", { fg = "#4d4d4d" })
hi(0, "TelescopeResultsField", { fg = "#a8a1be" })
hi(0, "TelescopeResultsFunction", { fg = "#a8a1be" })
hi(0, "TelescopeResultsIdentifier", { fg = "#dadada" })
hi(0, "TelescopeResultsLineNr", { bg = "#141414", fg = "#5b5b5b" })
hi(0, "TelescopeResultsMethod", {})
hi(0, "TelescopeResultsNormal", { bg = "#242424", fg = "#848484" })
hi(0, "TelescopeResultsNumber", { fg = "#b99bb5" })
hi(0, "TelescopeResultsOperator", { fg = "#bfad9d" })
hi(0, "TelescopeResultsSpecialComment", { fg = "#cbaa88" })
hi(0, "TelescopeResultsStruct", {})
hi(0, "TelescopeResultsTitle", { bg = "#242424", fg = "#242424" })
hi(0, "TelescopeResultsVariable", { fg = "#cbaa88" })
hi(0, "TelescopeSelection", { bg = "#323232" })
hi(0, "TelescopeSelectionCaret", { fg = "#242424" })
hi(0, "TelescopeTitle", { fg = "#242424" })
hi(0, "TermCursor", { link = "Cursor" })
hi(0, "TermCursorNC", { bg = "#4d4d4d" })
hi(0, "Title", { fg = "#cbaa88" })
hi(0, "Todo", { bg = "#32322c", fg = "#939374" })
hi(0, "Type", { fg = "#bfad9d" })
hi(0, "Underlined", { fg = "#848484", underline = true })
hi(0, "VertSplit", { bg = "#1a1a1a", fg = "#4d4d4d" })
hi(0, "Visual", { bg = "#2d2d2d" })
hi(0, "VisualNOS", { bg = "#282828" })
hi(0, "WarningMsg", { fg = "#d59192" })
hi(0, "Whitespace", { fg = "#4d4d4d" })
hi(0, "WildMenu", { link = "PmenuSel" })
hi(0, "lCursor", { link = "Cursor" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1a1a1a"
g.terminal_color_1 = "#d59192"
g.terminal_color_2 = "#b3b393"
g.terminal_color_3 = "#bfaf8e"
g.terminal_color_4 = "#a8a1be"
g.terminal_color_5 = "#b99bb5"
g.terminal_color_6 = "#a8a1be"
g.terminal_color_7 = "#5b5b5b"
g.terminal_color_8 = "#242424"
g.terminal_color_9 = "#ffbcbd"
g.terminal_color_10 = "#dfdfbe"
g.terminal_color_11 = "#ecdbb9"
g.terminal_color_12 = "#d4cdeb"
g.terminal_color_13 = "#e6c6e1"
g.terminal_color_14 = "#d4cdeb"
g.terminal_color_15 = "#aeaeae"
