-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "mellifluous-light"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#a3692e" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@constant.builtin", { link = "Constant" })
hi(0, "@constant.macro", { link = "Constant" })
hi(0, "@constructor", { link = "Function" })
hi(0, "@danger", { fg = "#953a32" })
hi(0, "@debug", { fg = "#a3692e" })
hi(0, "@define", { link = "PreProc" })
hi(0, "@environment", { fg = "#a3692e" })
hi(0, "@environment.name", { link = "@environment" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { fg = "#a3692e" })
hi(0, "@field", { fg = "#2e2e2e" })
hi(0, "@function.builtin", { link = "Function" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@include", { fg = "#544483" })
hi(0, "@keyword.function", { fg = "#ab3636" })
hi(0, "@keyword.operator", { fg = "#a3692e" })
hi(0, "@keyword.return", { fg = "#ab3636" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.enum", { link = "Type" })
hi(0, "@lsp.type.enumMember", { link = "Constant" })
hi(0, "@lsp.type.escapeSequence", { fg = "#707070" })
hi(0, "@lsp.type.formatSpecifier", { link = "Operator" })
hi(0, "@lsp.type.namespace", { link = "Type" })
hi(0, "@lsp.type.operator", { link = "Operator" })
hi(0, "@lsp.type.parameter", { fg = "#2e2e2e" })
hi(0, "@lsp.type.property", { fg = "#2e2e2e" })
hi(0, "@lsp.typemod.keyword.controlFlow", { fg = "#ab3636" })
hi(0, "@lsp.typemod.variable.constant", { link = "Constant" })
hi(0, "@math", { fg = "#a3692e" })
hi(0, "@namespace", { fg = "#8a6647" })
hi(0, "@note", { fg = "#51512a" })
hi(0, "@parameter", { fg = "#2e2e2e" })
hi(0, "@parameter.reference", { link = "@parameter" })
hi(0, "@property", { link = "@field" })
hi(0, "@punctuation.bracket", { fg = "#707070" })
hi(0, "@punctuation.delimiter", { fg = "#707070" })
hi(0, "@punctuation.special", { fg = "#707070" })
hi(0, "@storage.class", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#a37c2e" })
hi(0, "@string.regex", { fg = "#a37c2e" })
hi(0, "@string.special", { fg = "#a37c2e" })
hi(0, "@symbol", { link = "Character" })
hi(0, "@tag", { link = "Keyword" })
hi(0, "@tag.attribute", { fg = "#544483" })
hi(0, "@tag.delimiter", { fg = "#707070" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Character" })
hi(0, "@text.reference", { fg = "#83447a" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { fg = "#a3692e" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#687e9c" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@variable.builtin", { fg = "#a3692e" })
hi(0, "@warning", { fg = "#956c32" })
hi(0, "Boolean", { fg = "#83447a" })
hi(0, "Character", { fg = "#a37c2e" })
hi(0, "CmpDocumentationBorder", { link = "VertSplit" })
hi(0, "CmpItemAbbrDefault", { fg = "#919191" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#8e8e67" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#919191" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#919191" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#a3692e" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#707070" })
hi(0, "CmpItemMenuDefault", { fg = "#919191" })
hi(0, "CmpScrollThumb", { link = "PmenuThumb" })
hi(0, "ColorColumn", { bg = "#dedede" })
hi(0, "Comment", { fg = "#8e8e67", italic = true })
hi(0, "Conceal", { fg = "#b3b3b3" })
hi(0, "Conditional", { fg = "#ab3636" })
hi(0, "Constant", { fg = "#83447a" })
hi(0, "Cursor", { bg = "#a3692e", fg = "#e6e6e6" })
hi(0, "CursorColumn", { bg = "#ededed" })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = "#ededed" })
hi(0, "CursorLineNr", { bg = "#e6e6e6", fg = "#919191" })
hi(0, "Delimiter", { link = "Operator" })
hi(0, "DiagnosticError", { fg = "#953a32" })
hi(0, "DiagnosticHint", { fg = "#634681" })
hi(0, "DiagnosticInfo", { fg = "#465e81" })
hi(0, "DiagnosticSignError", { bg = "#dedede", fg = "#953a32" })
hi(0, "DiagnosticSignHint", { bg = "#dedede", fg = "#634681" })
hi(0, "DiagnosticSignInfo", { bg = "#dedede", fg = "#465e81" })
hi(0, "DiagnosticSignWarn", { bg = "#dedede", fg = "#956c32" })
hi(0, "DiagnosticUnderlineError", { underline = true })
hi(0, "DiagnosticUnderlineHint", { underline = true })
hi(0, "DiagnosticUnderlineInfo", { underline = true })
hi(0, "DiagnosticUnderlineWarn", { underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#f5f5f5", fg = "#953a32" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#f5f5f5", fg = "#634681" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#f5f5f5", fg = "#465e81" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#f5f5f5", fg = "#956c32" })
hi(0, "DiagnosticWarn", { fg = "#956c32" })
hi(0, "DiffAdd", { bg = "#d4d4c4" })
hi(0, "DiffChange", { bg = "#dfdad3" })
hi(0, "DiffDelete", { bg = "#dacac8" })
hi(0, "DiffText", { bg = "#d5cbbe" })
hi(0, "Directory", { fg = "#544483" })
hi(0, "EndOfBuffer", { fg = "#e6e6e6" })
hi(0, "Error", { fg = "#953a32" })
hi(0, "ErrorMsg", { fg = "#953a32" })
hi(0, "Exception", { fg = "#a3692e" })
hi(0, "Float", { fg = "#83447a" })
hi(0, "FloatBorder", { bg = "#f5f5f5", fg = "#f5f5f5" })
hi(0, "FloatShadow", { bg = "#dedede" })
hi(0, "FloatTitle", { bg = "#f5f5f5", fg = "#8e8e67" })
hi(0, "FoldColumn", { link = "Normal" })
hi(0, "Folded", { bg = "#f5f5f5", fg = "#707070" })
hi(0, "Function", { fg = "#544483" })
hi(0, "GitSignsAdd", { bg = "#dedede", fg = "#c2c23d" })
hi(0, "GitSignsChange", { bg = "#dedede", fg = "#dba457" })
hi(0, "GitSignsDelete", { bg = "#dedede", fg = "#db6257" })
hi(0, "GitSignsStagedAdd", { bg = "#dedede", fg = "#61611e" })
hi(0, "GitSignsStagedAddLn", { bg = "#d4d4c4" })
hi(0, "GitSignsStagedAddNr", { bg = "#dedede", fg = "#61611e" })
hi(0, "GitSignsStagedChange", { bg = "#dedede", fg = "#6d522b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#dfdad3" })
hi(0, "GitSignsStagedChangeNr", { bg = "#dedede", fg = "#6d522b" })
hi(0, "GitSignsStagedChangedelete", { bg = "#dedede", fg = "#6d522b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#dfdad3" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = "#dedede", fg = "#6d522b" })
hi(0, "GitSignsStagedDelete", { bg = "#dedede", fg = "#6d312b" })
hi(0, "GitSignsStagedDeleteNr", { bg = "#dedede", fg = "#6d312b" })
hi(0, "GitSignsStagedTopdelete", { bg = "#dedede", fg = "#6d312b" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = "#dedede", fg = "#6d312b" })
hi(0, "Identifier", { fg = "#2e2e2e" })
hi(0, "Ignore", { fg = "#b3b3b3" })
hi(0, "IncSearch", { bg = "#a3692e", fg = "#e6e6e6" })
hi(0, "IndentBlanklineChar", { fg = "#cfcfcf" })
hi(0, "IndentBlanklineContextChar", { fg = "#b3b3b3" })
hi(0, "IndentBlanklineContextStart", { sp = "#ab3636", underline = true })
hi(0, "IndentBlanklineSpaceChar", { link = "Whitespace" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#b3b3b3", nocombine = true })
hi(0, "Keyword", { fg = "#a3692e" })
hi(0, "Label", { fg = "#ab3636" })
hi(0, "LineNr", { bg = "#dedede", fg = "#919191" })
hi(0, "LspCodeLens", { bg = "#ededed" })
hi(0, "LspCodeLensSeparator", { fg = "#b3b3b3" })
hi(0, "LspReferenceRead", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = "#f5f5f5" })
hi(0, "LspReferenceWrite", { link = "LspReferenceText" })
hi(0, "LspSignatureActiveParameter", { bg = "#fcfcfc" })
hi(0, "MatchParen", { bg = "#fcfcfc", fg = "#ab3636" })
hi(0, "ModeMsg", { fg = "#707070" })
hi(0, "MoreMsg", { fg = "#a3692e" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { link = "VertSplit" })
hi(0, "NonText", { link = "Conceal" })
hi(0, "Normal", { bg = "#e6e6e6", fg = "#2e2e2e" })
hi(0, "NormalFloat", { bg = "#f5f5f5" })
hi(0, "Number", { fg = "#83447a" })
hi(0, "NvimTreeBookmark", { fg = "#51512a" })
hi(0, "NvimTreeEndOfBuffer", { fg = "#e6e6e6" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#51512a" })
hi(0, "NvimTreeFolderIcon", { fg = "#544483" })
hi(0, "NvimTreeGitDeleted", { fg = "#953a32" })
hi(0, "NvimTreeGitDirty", { fg = "#956c32" })
hi(0, "NvimTreeGitIgnored", { fg = "#b3b3b3" })
hi(0, "NvimTreeGitMerge", { fg = "#634681" })
hi(0, "NvimTreeGitNew", { fg = "#465e81" })
hi(0, "NvimTreeGitRenamed", { fg = "#956c32" })
hi(0, "NvimTreeGitStaged", { fg = "#51512a" })
hi(0, "NvimTreeImageFile", { bold = true, fg = "#634681" })
hi(0, "NvimTreeIndentMarker", { fg = "#544483" })
hi(0, "NvimTreeLiveFilterPrefix", { bold = true, fg = "#634681" })
hi(0, "NvimTreeLiveFilterValue", { bold = true })
hi(0, "NvimTreeModifiedFile", { fg = "#51512a" })
hi(0, "NvimTreeNormal", { bg = "#dedede", fg = "#4f4f4f" })
hi(0, "NvimTreeOpenedFile", { bold = true, fg = "#51512a" })
hi(0, "NvimTreePopup", { link = "NvimTreeNormal" })
hi(0, "NvimTreeRootFolder", { fg = "#dedede" })
hi(0, "NvimTreeSpecialFile", { bold = true, fg = "#a37c2e", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#465e81" })
hi(0, "NvimTreeWinSeparator", { bg = "#dedede", fg = "#f5f5f5" })
hi(0, "NvimTreeWindowPicker", { bg = "#4493c8", bold = true, fg = "#ededed" })
hi(0, "Operator", { fg = "#707070" })
hi(0, "Pmenu", { bg = "#fcfcfc", fg = "#919191" })
hi(0, "PmenuSbar", { bg = "#f5f5f5" })
hi(0, "PmenuSel", { bg = "#dedede" })
hi(0, "PmenuThumb", { bg = "#b3b3b3" })
hi(0, "PreProc", { fg = "#544483" })
hi(0, "Question", { fg = "#a3692e" })
hi(0, "QuickFixLine", { link = "Normal" })
hi(0, "Repeat", { fg = "#ab3636" })
hi(0, "Search", { bg = "#fcfcfc", fg = "#2e2e2e" })
hi(0, "SignColumn", { link = "LineNr" })
hi(0, "Special", { fg = "#a3692e" })
hi(0, "SpecialKey", { fg = "#a3692e" })
hi(0, "SpellBad", { fg = "#953a32" })
hi(0, "SpellCap", { fg = "#956c32" })
hi(0, "SpellLocal", { fg = "#956c32" })
hi(0, "SpellRare", { fg = "#956c32" })
hi(0, "StartifyBracket", { fg = "#919191" })
hi(0, "StartifyNumber", { fg = "#2e2e2e" })
hi(0, "StartifyPath", { fg = "#465e81" })
hi(0, "StartifySlash", { link = "StartifyPath" })
hi(0, "Statement", { fg = "#a3692e" })
hi(0, "StatusLine", { bg = "#fcfcfc", fg = "#4f4f4f" })
hi(0, "StatusLineNC", { bg = "#ededed", fg = "#919191" })
hi(0, "Stl366b8a_fcfcfc__", { bg = "#fcfcfc", fg = "#366b8a" })
hi(0, "Stl4f4f4f_fcfcfc__", { bg = "#fcfcfc", fg = "#4f4f4f" })
hi(0, "Stlgrey_fcfcfc__", { bg = "#fcfcfc", fg = "#808080" })
hi(0, "String", { fg = "#a37c2e" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { bg = "#fcfcfc", fg = "#707070" })
hi(0, "TabLineFill", { link = "TabLine" })
hi(0, "TabLineSel", { bg = "#ededed", fg = "#4f4f4f" })
hi(0, "TelescopeBorder", { fg = "#ededed" })
hi(0, "TelescopeMatching", { fg = "#2e2e2e" })
hi(0, "TelescopeNormal", { bg = "#ededed", fg = "#707070" })
hi(0, "TelescopePreviewBorder", { bg = "#ededed", fg = "#ededed" })
hi(0, "TelescopePreviewLine", { bg = "#dedede" })
hi(0, "TelescopePreviewNormal", { bg = "#ededed" })
hi(0, "TelescopePreviewTitle", { fg = "#707070" })
hi(0, "TelescopePromptBorder", { bg = "#ededed", fg = "#ededed" })
hi(0, "TelescopePromptCounter", { fg = "#919191" })
hi(0, "TelescopePromptNormal", { bg = "#ededed" })
hi(0, "TelescopePromptTitle", { bg = "#4f4f4f", fg = "#e6e6e6" })
hi(0, "TelescopeResultsBorder", { bg = "#ededed", fg = "#ededed" })
hi(0, "TelescopeResultsTitle", { bg = "#ededed", fg = "#ededed" })
hi(0, "TelescopeSelection", { bg = "#dedede" })
hi(0, "TelescopeSelectionCaret", { fg = "#ededed" })
hi(0, "TermCursor", { link = "Cursor" })
hi(0, "TermCursorNC", { bg = "#b3b3b3" })
hi(0, "Title", { fg = "#a3692e" })
hi(0, "Todo", { bg = "#a37c2e", fg = "#e6e6e6" })
hi(0, "Type", { fg = "#8a6647" })
hi(0, "Underlined", { fg = "#707070", underline = true })
hi(0, "VertSplit", { bg = "#e6e6e6", fg = "#b3b3b3" })
hi(0, "Visual", { bg = "#cfcfcf" })
hi(0, "VisualNOS", { bg = "#f5f5f5" })
hi(0, "WarningMsg", { fg = "#953a32" })
hi(0, "Whitespace", { fg = "#b3b3b3" })
hi(0, "WildMenu", { link = "PmenuSel" })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "nvim_set_hl_x_hi_clear_bugfix", { fg = "#ff0000" })
hi(0, "rainbowcol1", { ctermfg = 9, fg = "#cc241d" })
hi(0, "rainbowcol2", { ctermfg = 10, fg = "#a89984" })
hi(0, "rainbowcol3", { ctermfg = 11, fg = "#b16286" })
hi(0, "rainbowcol4", { ctermfg = 12, fg = "#d79921" })
hi(0, "rainbowcol5", { ctermfg = 13, fg = "#689d6a" })
hi(0, "rainbowcol6", { ctermfg = 14, fg = "#d65d0e" })
hi(0, "rainbowcol7", { ctermfg = 15, fg = "#458588" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#e6e6e6"
g.terminal_color_1 = "#953a32"
g.terminal_color_2 = "#51512a"
g.terminal_color_3 = "#a37c2e"
g.terminal_color_4 = "#465e81"
g.terminal_color_5 = "#634681"
g.terminal_color_6 = "#465e81"
g.terminal_color_7 = "#919191"
g.terminal_color_8 = "#ededed"
g.terminal_color_9 = "#bb493e"
g.terminal_color_10 = "#79793e"
g.terminal_color_11 = "#c79738"
g.terminal_color_12 = "#5777a2"
g.terminal_color_13 = "#7d57a2"
g.terminal_color_14 = "#5777a2"
g.terminal_color_15 = "#4f4f4f"
